### ISSUE TITLE
Predicted next cycle does not include titan kill (minor cosmetic)

### ISSUE THREAD

**Issue by Charybdis** [DarkSession/EDOverwatch#10]
After defeating Hadad this week, and the Intermediate result correctly showing a Titan kill, the predicted next cycle does not include this information.

In the grand scheme of things this is a minor cosmetic issue on a most useful site.

![image](https://github.com/DarkSession/EDOverwatch/assets/23155785/5c25a66f-0c57-4375-89db-cd134502c8ef)

**Comment by DarkSession** [comment]
The idea is to have the same numbers there as in-game.
FDev made the decision to only remove the Titan system from the in-game war overview after 2 cycles. Since a tick just happened and the numbers from the "next cycle" should be the current numbers in-game we can compare:
![image](https://github.com/DarkSession/EDOverwatch/assets/68336675/8c849b0a-f6e4-45e3-9ddf-92b48499c727)

Only in the next cycle the Titan is no longer counted in-game. Therefore, also in Overwatch it will be visible like that:
![image](https://github.com/DarkSession/EDOverwatch/assets/68336675/e4632cf5-e7c2-4597-848a-b4c1c4690835)

**Comment by Charybdis** [comment]
Ah that's fair enough, if a somewhat counter-intuitive.

There's still something a little strange going on here though: I'm now seeing 6 titans reported as active! Is this a function of the tick occuring part the way through the day?

![image](https://github.com/DarkSession/EDOverwatch/assets/23155785/a8c58d75-0f36-4ed3-a555-d22c2d340d06)

Thanks for the quick response!

**Comment by Charybdis** [comment]
Tinfoil hat time: do we need to be looking for another incoming Titan?

**Comment by DarkSession** [comment]
Thanks for your feedback.
Indeed there is one Titan too much in there. :smile:
Looks like some old code reactivated Taranis. I updated Taranis manually, already removed the old code that I suspect reactivated it and will deploy it in the next days.

**Comment by Charybdis** [comment]
Thanks for the update and taking a deeper look. I don't know of any other community that has this level of technical expertise available in external tools. It really is an awesome site.

o7 CMDR.

**Comment by DarkSession** [comment]
Thank you, appreciated. o7
